### ISSUE TITLE
exports exist in pdf but do not exist in excel yet

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1002]
This library may help in harmonizing outputs to pdf and excel

This may help https://github.com/Ideolys/carbone

**Comment by juan-rivera-2020** [comment]
**Note 1:**  I extracted the message below from the[ vue-json-excel](https://www.npmjs.com/package/vue-json-excel) npm site.  Basically, the prompt before opening the Excel file is a Microsoft "thing", not a bug.  Aside from this message, the exports work fine.  
**Note 2:**
The Team Excel export works.  However, it is the only one in the Client Panel (Facility Manager and Sheets) that doesn't print out the User's sort order.  It currently prints out the Team list in alphabetical order (by Last Name).  This seems to be due to a compatibility issue with the particular library used for the Team data table (as it wasn't an issue anywhere else in the Client Panel).

-"Extra prompt in Microsoft Excel
The method implemented in this component uses HTML tables to draw the .xls files, Microsoft Excel no longer recognize HTML as native content so a warning message will be displayed before opening the file. The content will be rendered perfectly but the message can't be avoided."
![image](https://user-images.githubusercontent.com/72885316/103101265-be26b580-45e4-11eb-83d6-768bb07e9690.png)
