### ISSUE TITLE
Last Update Column not sorting by date.  Should it?

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mGis#1080]
Like **On Watch** and **Overdue** columns, **Last Update** column currently sorts by presence of an update or not.  UX may be improved by sorting by latest update date.

**Comment by juan-rivera-2020** [comment]
Please close if this is a non-issue.

**Comment by bluenevus** [comment]
well the last column should be sortable preferably by date because that is the utility

**Comment by juan-rivera-2020** [comment]
Sounds good...Will fix.

**Comment by JuanCodeAtATime** [comment]
The current solution for this (until a more optimal one is found) is to remove the “No Update” string so that string doesn’t interfere with the  sorting of the dates.  

Sorting by date was my original goal at the onset of this task, but accurate sorting of that column was presenting an issue.  It wasn’t sorting properly.  

Through some troubleshooting, I discovered that removing the “No Update” string allowed the dates to sort in order (asc and desc).   

I also enhanced the UI of the update rows to offset the blank-white rows that don’t have updates.  

PR will be #1030 which will be sent today.
