### ISSUE TITLE
admin/projects - Add/Edit forms - Advanced tab: User should be able to multiselect options and switch between included and not included.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#1137]
Screenshot Example

![admin_projects_advanced_enumerations_select_more_than_one_then_switch](https://user-images.githubusercontent.com/11938477/101686264-d15b5200-3a36-11eb-838a-75f77d1e66ac.png)

**Comment by bluenevus** [comment]
they should be able to multiselect

**Comment by microhealthamand** [comment]
It wasn't working because of the javascript error which I have fixed. But current functionality is when the user clicks on the user name on the left, it will move to the right and vice versa. Do we want to change that?  The icon left and right is just for show, nothing will happen if we click on it right now.

**Comment by bluenevus** [comment]
You want to be able to select more than one user as a time to then move over to the right

**Comment by LAlexMHllc** [comment]
Closing, because this will be handled by search/select
