### ISSUE TITLE
Add Risk Approach Approver, Approved checkbox, and Approval Date

### ISSUE THREAD

**Issue by juan-rivera-2020** [MicroHealthLLC/mGis#1734]
More information available in mGIS Risks Overview Documentation (Sharepoint > IT Apps > mGIS > Designs > mGIS Risks Overview.docx)

![image](https://user-images.githubusercontent.com/72885316/107779020-ceb8f980-6d12-11eb-9aa2-65f75d65208d.png)

**Comment by LAlexMHllc** [comment]
Alert incorrectly displayed when the selected Risk Approach Approver tried to check Approved checkbox.
Screenshot Example

![risk_alert_when_selected_approver_checked_approved](https://user-images.githubusercontent.com/11938477/108226684-1e306880-710b-11eb-914d-d26d603f9849.png)

**Comment by LAlexMHllc** [comment]
Unable to deselect Risk Approach Approver.
Screenshot Example

![unable_deselect_risk_approach_approver](https://user-images.githubusercontent.com/11938477/108227427-e37b0000-710b-11eb-9b55-f0b0821f1f6b.png)

**Comment by LAlexMHllc** [comment]
User clicked Save, then edit same risk. "null" displayed for Date/Time Risk Approach Approved.
Screenshot Example

![date-time-risk-approach-approved_value_null](https://user-images.githubusercontent.com/11938477/108228071-83d12480-710c-11eb-8849-d8486f276058.png)

**Comment by LAlexMHllc** [comment]
User edit same risk, then saved risk with completed Approved section.
Screenshot Example

![saved_risk_with_completed_approved_section](https://user-images.githubusercontent.com/11938477/108229867-2dfd7c00-710e-11eb-8330-e1a8f76d0747.png)

**Comment by LAlexMHllc** [comment]
User edit same risk and Approver was enabled with Approved unchecked. User was able to select a different Approver, then save.
Screenshot Example

![risk_different_approver_selected_after_risk_saved_after_approver_checked_approved](https://user-images.githubusercontent.com/11938477/108231640-f2fc4800-710f-11eb-9c78-788701d3c960.png)

**Comment by juan-rivera-2020** [comment]
If Risk Approver is undefined, the form will not allow user to open Risks PRIORITIZE tab.  Currently fixing this issue. 
![image](https://user-images.githubusercontent.com/72885316/108372145-81360400-71cc-11eb-9fbe-e35113c297c3.png)

**Comment by LAlexMHllc** [comment]
1. Not able to check Approved when logged in user in selected Approver.

2. Not able to deselect approver.

3. Alert did not display when non-approver checked Approver.

4. Saved risk with Approver selected. When edit same risk, no approver selected.

5. Clicking Reset RISK APPROVER SECTION closed the form.

**Comment by LAlexMHllc** [comment]
Include Approver message on Edit Risk form
Screenshot Example

![include_approver_message_on_edit_form](https://user-images.githubusercontent.com/11938477/108536446-794c9180-72aa-11eb-95b0-1fe0f4eb7922.png)

**Comment by bluenevus** [comment]
I don't understand this section of risks.  doesn't work.  even with the description, entering the name removes teh approved then the date says null.  If it doesn't work and we aren't getting to it, we need to hide it as its quite confusing

![image](https://user-images.githubusercontent.com/3675043/115101065-3d7f2280-9f0f-11eb-9080-092ea01a187c.png)

**Comment by bluenevus** [comment]
if the workflow is to get an approval, it really makes more sense under the assign section 

![image](https://user-images.githubusercontent.com/3675043/115112897-8eb20500-9f55-11eb-9f6f-d0725854efbe.png)

Also, the two step save is really confusing and rarely will someone request a risk approval then someone else go in and click it making it pretty useless as it stand

the person entering the risk will almost ALWAYS do it on behalf of the approver so we need to significantly simplify it and show if the approver does it, approved by them.  if the person entering the data does it, its on behalf of the approver.  Either way, its nothing elaborate, we keep it simple because until we think through a routing system for approval, the person entering the approval will literally approve on behalf of their boss so make it ridiculously simple to do so and show that it was signed on behalf of a person in the 90% percent of the time it will be done that way and when its not, well, the person signing it can sign it themselves

**Comment by LAlexMHllc** [comment]
Closing, since requirements are changing.
