### ISSUE TITLE
update activerecord now - high priority

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mGis#1896]
![image](https://user-images.githubusercontent.com/3675043/109648922-32239380-7b29-11eb-8e4b-cbf6fc1fbc84.png)

**Comment by microhealthamand** [comment]
To update Active record to  5.2.4.5  I have to update Rails because current rails version is dependent on  5.2.4.4 and so it is giving error of dependency. However current version i.e. 5.2.4.4 will not affect us because as per detail given here `This only impacts Rails applications that are using PostgreSQL along with money type columns that take user input.`  We aren't using Postgresql database and not using Money type column.

But I will update our app to latest Rails and Ruby version

**Comment by LAlexMHllc** [comment]
Closing, since version updated
