### ISSUE TITLE
Some Task form selected items missing green background style

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#2027]
Screenshot Examples

![task_form_category_stage_responsible_accountable_without_green_style](https://user-images.githubusercontent.com/11938477/111181310-379ac800-8584-11eb-8ac0-9ab0b3f7b8f2.png)

**Comment by juan-rivera-2020** [comment]
I don't recall this being any different.  It's like this in prod which probably wasn't recently introduced.  So I think it's by design and not a bug.  The multi-select options have the green background style if you can select more than one.  The single-select items don't have a background color.  Can you check/confirm?
