### ISSUE TITLE
Project dashboard - Facility Summary - Tasks tab: Include Facility Name above Task forms so it is clear to the user which facility the task is being added to or edited.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#354]
For Add Task - the issue is if the user clicks another facility icon on the map, the task will be added to that facility on submit, not the original facility the Add a new Task form was opened for.

Edit Task results in inconsistent results when change facility after form displayed and submitted.

Screenshot Example

![facility_summary_tasks_forms_include_facility_name](https://user-images.githubusercontent.com/11938477/85065048-84c74600-b17a-11ea-911c-ff959567d072.png)

**Comment by bluenevus** [comment]
[cid:image001.png@01D64589.458CA690]
Should probably display above the tab below

[cid:image002.png@01D64589.458CA690]

So that its always there vs adding one on every tab

Frank Tucker
Chief Executive Officer, Executive Office
t: 855-294-3547
m: 571-327-1211
frank.tucker@microhealthllc.com | www.microhealthllc.com
8229 Boone Blvd ​Ste 500, ​Vienna, VA 22182
This communication and attachments may contain confidential, proprietary or privileged information for only the intended recipient. If you are not the intended recipient, disclosing, distributing, copying, or using this communication is strictly prohibited. If you received this message in error, please notify the sender immediately by return email and delete it from your system.

**Comment by bluenevus** [comment]
more like this so we only have to put it in one location and that location is consistent.  This way we don't have to put it on every form which we shouldn't.  One place that is static like below

![image](https://user-images.githubusercontent.com/3675043/85066327-c2c56980-b17c-11ea-879b-4b9702c91061.png)

**Comment by bluenevus** [comment]
simply adding on the top of the form
