### ISSUE TITLE
Facility Summary - Task forms: auto calculate Task Progress % based on checked checklist items comparison to total checklist items

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#403]
Screenshot Example

![facility_summary_task_progress_autocalculate_checked_checklist](https://user-images.githubusercontent.com/11938477/86630320-ae65d700-bf9a-11ea-97a1-cbf86f9dd134.png)

**Comment by LAlexMHllc** [comment]
NOTE: When Issue #403 is complete, then should:
- auto complete Facility Project % under Overview tab
- remove Progress from Admin/Tasks - Edit Task form

**Comment by bluenevus** [comment]
We should auto move the progress bar but I don't think we should remove it because there will be tasks with out checklists where they will need to move the bar manually.  So the user will override, give a warning and once accepted, they must manually update because they chose to overide and disable auto complete progress.  Or maybe its a default box next to the progress bar that says autocomplete and they will have to uncheck it if they want to do it manually here this way they have the ability to go back to autocomplete progress
