### ISSUE TITLE
admin/users - Edit User: Should be able to Update User without changing Password; Invalid message displayed.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#631]
Screenshot Example

![admin_edit_user_should_be_able_to_update_without_changing_password](https://user-images.githubusercontent.com/11938477/96750727-4a74ec00-139a-11eb-80a6-1e38dbaf62d4.png)

**Comment by bluenevus** [comment]
well it depends.  if the current password does not meet the requirements configured in the system then its working as designed and the password has to be changed to meet the current standards.  However, if it meets the current standard and its asking, then its a bug

**Comment by LAlexMHllc** [comment]
Failed validation when password is blank (when not updating password), and when a valid password is input (could be existing or to change password). All fail validation.

**Comment by bluenevus** [comment]
turns out no mater what you do it will always result in the faild validation.  clicking the generator will result in a failed validation so the generator isn't matching the settings.  The bigger issue is the setting page is now blank.  clicking settings results in this 
![image](https://user-images.githubusercontent.com/3675043/97332565-f8780e80-1850-11eb-8886-62881802885d.png)
