### ISSUE TITLE
Include "Completed Date" for Tasks and Issues

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mGis#644]
Include "Completed Date" (datepicker)

Admin Panel
_________________________________________________________

admin/tasks: new and edit forms
admin/facilities: Batch Actions - Add Task Selected
admin/issues: edit form

Client Panel
__________________________________________________________

Tasks: new and edit forms
Issues: new and edit forms

**Comment by bluenevus** [comment]
If the users request this then the estimated completion date should be "Due Date" so that in reports they can see the difference between actual due date and completion date.  I'm just not sure this is a priority right now so hold on this as I'm now running the projects and the features most important must address what I need first
